package co.edu.uptc.controller;

public enum Actions {
	BUTTON_ANALISIS_GEO,
	BUTTON_ANALISIS_VEHI,
	BUTTON_GEO_OPCIONONE,
	BUTTON_GEO_OPCIONDOS,
	BUTTON_GEO_OPCIONTRES,
	BUTTON_VEH_OPCIONONE,
	BUTTON_VEH_OPCIONDOS,
	BUTTON_VEH_OPCIONTRES,
	EXIT,
	
	
	
}
